### ISSUE TITLE
Сборник мыслей по Заданию №1

### ISSUE THREAD

**Issue by OITBsuir** [N1kman/Internship-Information-Technology-Department#1]
1) Названия таблиц во множественном числе обычно стараются избегать, хотя, если все в едином стиле, то можно попробовать и во множественном.

2) Оправдано ли использование естественных ключей вместо суррогатных в таблицах (например, passport_id в clients: документ может меняться со временем)?

3) Что такое seats? Количество мест в самолете? Можно вместе с aircrafts.model в отдельную таблицу вынести или неспосредственно в aircrafts, если seats это просто характеристика самолета. 
Но тут, скорее всего, это характеристика конкретного места на конкретный полет. Можно ли seats в таком случае связать с flights?

4) Может тогда и статус из tickets перекачует в seat?

5) Возможно, для flights.flight_date тип date/timestamp логичнее вместо обычной строки?

6) tickets.code и tickets.seat_code не одно ли и то же? Если нет, то названия надо бы разные придумать. tickets.seat_code случайно не кандидат во внешние ключи на seats?

7) Названия внешних ключей не соответствуют общепринятым naming conventions. В history более-менее еще. 

8) fk_... - это больше про название constraint, а не сам внешний ключ (касается практически всех внешних ключей в выполненном задании). Кроме того, с названием constraint в history тогда также беда.

**Comment by N1kman** [comment]
> 1. Названия таблиц во множественном числе обычно стараются избегать, хотя, если все в едином стиле, то можно попробовать и во множественном.
> 2. Оправдано ли использование естественных ключей вместо суррогатных в таблицах (например, passport_id в clients: документ может меняться со временем)?
> 3. Что такое seats? Количество мест в самолете? Можно вместе с aircrafts.model в отдельную таблицу вынести или неспосредственно в aircrafts, если seats это просто характеристика самолета.
>    Но тут, скорее всего, это характеристика конкретного места на конкретный полет. Можно ли seats в таком случае связать с flights?
> 4. Может тогда и статус из tickets перекачует в seat?
> 5. Возможно, для flights.flight_date тип date/timestamp логичнее вместо обычной строки?
> 6. tickets.code и tickets.seat_code не одно ли и то же? Если нет, то названия надо бы разные придумать. tickets.seat_code случайно не кандидат во внешние ключи на seats?
> 7. Названия внешних ключей не соответствуют общепринятым naming conventions. В history более-менее еще.
> 8. fk_... - это больше про название constraint, а не сам внешний ключ (касается практически всех внешних ключей в выполненном задании). Кроме того, с названием constraint в history тогда также беда.

1-2. fixed.
3. Это места самолета. У каждого самолета может разное количество мест и их нумерация, по этим местам далее генерируются билеты. Связать с flight?. Есть идея - сделать связь многие ко многим, то есть у рейса есть выделенные места, и уже через эту связь можно добираться к номеру места, ну и следовательно генерировать билеты через эту связь. 
4. В seat точно нет (статус показывает была ли бронь билета, а не места, то есть одно и тоже место может быть забронировано в двух разных рейсах. Но если делать, как описал выше, то можно перенести статус в смежную таблицу (flight-seat).
5. fixed.
6. Нет, это разное. Но тут как-бы номер места и номер билета. Логично же так и называть. Но если это чему-то противоречит, то готов поменять. И опять же номера мест могут быть организованы и схожи в разных самолетах, поэтому нет.
7-8. fixed.

Бизнес-логика следующая:
1) Компания задает рейс в котором участвует самолет
(У самолета есть места [seat_number - номер места]).
2) Далее на основании мест самолета генерируются билеты.
3) Клиент может забронировать билет (один билет - бронируется единожды),
ticket-status показывает, был ли забронирован билет.

**Comment by OITBsuir** [comment]
Если я правильно понимаю, то логика с местами следующая. Есть, например, самолет А. У него в базе создано 10 мест. При создании рейса с участием самолета А мы проходимся по его 10 местам и генерируем на них 10 билетов, соответственно для следующего рейса сформируются новые 10 билетов на те же самые места. То есть в базе всегда 10 мест самолета А и каждый раз генерируются новые 10 билетов. На данный момент так?

Как от билета попасть к месту в самолете? Лучше, видимо, связать билет с местом через внешний ключ и убрать seat_number из билета. В остальном как будто бы нормально.

**Comment by N1kman** [comment]
> Если я правильно понимаю, то логика с местами следующая. Есть, например, самолет А. У него в базе создано 10 мест. При создании рейса с участием самолета А мы проходимся по его 10 местам и генерируем на них 10 билетов, соответственно для следующего рейса сформируются новые 10 билетов на те же самые места. То есть в базе всегда 10 мест самолета А и каждый раз генерируются новые 10 билетов. На данный момент так?
> 
> Как от билета попасть к месту в самолете? Лучше, видимо, связать билет с местом через внешний ключ и убрать seat_number из билета. В остальном как будто бы нормально.

Да, именно так. А, ну да, так будет оптимально.
